# Generated by Django 2.2.11 on 2020-04-16 19:49

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_forms.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0024_auto_20200410_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_forms_formdefinition', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=255, verbose_name='Form Name')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('submit_btn_txt', models.CharField(default='Submit', help_text="Text for the Submit Button. The default is 'Submit'", max_length=100, verbose_name='Submit Button Text')),
                ('post_submit_msg', models.TextField(blank=True, default='Thank You', help_text='Display this message to users after they submit your form.', verbose_name='Post Submit Message')),
                ('success_redirect', models.BooleanField(default=False, help_text='HTTP redirect after successful submission', verbose_name='Redirect?')),
                ('external_redirect', models.URLField(blank=True, help_text='e.g. http://example.com/thank-you', verbose_name='External URL')),
                ('redirect_delay', models.PositiveIntegerField(blank=True, help_text='Wait this number of milliseconds before redirecting. 1000 milliseconds = 1 second.', null=True, verbose_name='Redirect Delay')),
                ('email_to', models.CharField(blank=True, help_text='Separate several addresses with a comma.', max_length=255, verbose_name='Send form data to e-mail address')),
                ('email_from', models.EmailField(blank=True, max_length=255, verbose_name='Sender Email Address')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='Email Subject')),
                ('email_uploaded_files', models.BooleanField(default=True, verbose_name='Send uploaded files as email attachments')),
                ('save_data', models.BooleanField(default=True, help_text='Logs all form submissions to the database.', verbose_name='Save to database')),
                ('spam_protection', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Honeypot'), (2, 'ReCAPTCHA')], default=0, verbose_name='Spam Protection')),
                ('form_template', models.CharField(blank=True, choices=[('djangocms_forms/form_template/default.html', 'Default')], default='djangocms_forms/form_template/default.html', max_length=150, verbose_name='Form Template')),
                ('page_redirect', cms.models.fields.PageField(blank=True, help_text='A page has priority over an external URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Page URL')),
                ('plugin_reference', djangocms_forms.fields.PluginReferenceField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin', to='djangocms_forms.Form')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('referrer', models.CharField(blank=True, max_length=150, verbose_name='Referrer URL')),
                ('form_data', jsonfield.fields.JSONField(verbose_name='Form Data')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('plugin', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='djangocms_forms.Form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'ordering': ('-creation_date',),
                'permissions': (('export_formsubmission', 'Can export Form Submission'),),
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('email', 'Email'), ('number', 'Number'), ('phone', 'Phone'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkbox_multiple', 'Multi Checkbox'), ('select', 'Drop down'), ('radio', 'Radio'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('password', 'Password'), ('hidden', 'Hidden')], default='text', max_length=100, verbose_name='Field Type')),
                ('label', models.CharField(max_length=255, verbose_name='name')),
                ('field_name', models.CharField(blank=True, max_length=255, verbose_name='Custom Field Name')),
                ('placeholder_text', models.CharField(blank=True, max_length=100, verbose_name='Placeholder Text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('help_text', models.TextField(blank=True, help_text='A description / instructions for this field.', verbose_name='Description')),
                ('initial', models.CharField(blank=True, max_length=255, verbose_name='Default Value')),
                ('choice_values', models.TextField(blank=True, help_text='Enter options one per line. For "File Upload" field type, enter allowed filetype (e.g .pdf) one per line.', verbose_name='Choices')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Position')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='djangocms_forms.FormDefinition')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'ordering': ('position',),
            },
        ),
    ]
