# Generated by Django 2.2.11 on 2020-04-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('cms', '0024_auto_20200410_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinkPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_quicklinkpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('quick_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.QuickLink')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NewsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_newspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.News')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MediaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_mediapluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Media')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DownloadsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_downloadspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('downloads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Downloads')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
